# name: Bitasmbl Validation

# on:
#   push:
#     branches: [main]

# jobs:
#   validate:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Validate project
#         run: echo "Running Bitasmbl validation..."


name: Bitasmbl Evaluate Diff

on:
  push:

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Extract metadata from bitasmbl.json
        id: meta
        run: |
          PROJECT_ID=$(jq -r '.projectId' bitasmbl.json)
          REQUIREMENT_ID=$(jq -r '.requirementId' bitasmbl.task.json)

          echo "project_id=$PROJECT_ID" >> $GITHUB_OUTPUT
          echo "requirement_id=$REQUIREMENT_ID" >> $GITHUB_OUTPUT

      - name: Get git diff
        id: diff
        run: |
          DIFF=$(git diff HEAD^ HEAD)
          DIFF_ESCAPED=$(printf '%s' "$DIFF" | jq -Rs .)

          echo "diff=$DIFF_ESCAPED" >> $GITHUB_OUTPUT

      - name: Send to backend
        run: |
          curl -X POST https://1c6c-176-221-143-53.ngrok-free.app/projects/evaluate-code-diff \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.BITASMBL_TOKEN }}" \
            -d "{
              \"projectId\": ${{ steps.meta.outputs.project_id }},
              \"requirementId\": ${{ steps.meta.outputs.requirement_id }},
              \"repo\": \"${{ github.repository }}\",
              \"commitSha\": \"${{ github.sha }}\",
              \"diff\": ${{ steps.diff.outputs.diff }}
            }"
