name: Bitasmbl Validation

on:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate project
        run: echo "Running Bitasmbl validation..."

      - name: Verify Token Existence
        run: |
          if [ -z "${{ secrets.BITASMBL_TOKEN }}" ]; then
            echo "TOKEN IS MISSING"
          else
            echo "TOKEN IS SET: ${{ secrets.BITASMBL_TOKEN }}"
          fi
          
